const router = require('./lib/router');



var testData = [
{"httpMethod":"post","path":"cargo/tracking/HEGQSIAYPT/QSNOMCJFZW"},
{"httpMethod":"get","path":"user/signup/BGPSNDQCWJ/KINYZHRBML"},
{"httpMethod":"post","path":"cargo/tracking/QTUDZEYMBP/ZNEWORVGMY"},
{"httpMethod":"get","path":"user/signup/QIVYRBLMJK/AMXOZPEQUW"},
{"httpMethod":"post","path":"cargo/tracking/JMYPWANCGD/QZCAUFJVSE"},
{"httpMethod":"get","path":"user/signup/VLUYMEODTP/LRPAVCDBUY"},
{"httpMethod":"post","path":"cargo/tracking/IRKGTVWODZ/UNZCPYOXTW"},
{"httpMethod":"get","path":"user/signup/BMIADCNQOY/YEDZMJUNFQ"},
{"httpMethod":"post","path":"cargo/tracking/DROAQBCUIF/IMJNUFWOHP"},
{"httpMethod":"get","path":"user/signup/OFLGTWKVQZ/GAETSNRHLP"},
{"httpMethod":"post","path":"cargo/tracking/PVSHIEKFJA/MJHCPGEFAS"},
{"httpMethod":"get","path":"user/signup/VNPLICYHRO/HMUNZDFBVE"},
{"httpMethod":"post","path":"cargo/tracking/SLKNFRHQPJ/BHYMTIQRNV"},
{"httpMethod":"get","path":"user/signup/TYFWNSZDAI/AJKXGWLUID"},
{"httpMethod":"post","path":"cargo/tracking/KLQFWJUITR/OCVMNBSGQT"},
{"httpMethod":"get","path":"user/signup/XSZADLOGVP/YFGEAMPJDI"},
{"httpMethod":"post","path":"cargo/tracking/WTBHVNEXMS/PXUHYICBTW"},
{"httpMethod":"get","path":"user/signup/DBVHYAOEJS/LRWOKVPYXA"},
{"httpMethod":"post","path":"cargo/tracking/LCHWDOYRJX/GYIFQLJTCW"},
{"httpMethod":"get","path":"user/signup/JXGNLKRCME/SXMFEDOWBN"},
{"httpMethod":"post","path":"cargo/tracking/MINJGLBRUO/NLVAOBEPZY"},
{"httpMethod":"get","path":"user/signup/XYUVLHIWAJ/EHDYFCNKJV"},
{"httpMethod":"post","path":"cargo/tracking/SBUTPNVGRA/UBDIGMECRX"},
{"httpMethod":"get","path":"user/signup/PERBSKOYGZ/QOAGVILXMN"},
{"httpMethod":"post","path":"cargo/tracking/YZNJSMBDCX/RHNPTCVFJW"},
{"httpMethod":"get","path":"user/signup/ZOTERYFGDX/IORQMBCWTD"},
{"httpMethod":"post","path":"cargo/tracking/ZIQTVLPWEJ/QMESNFZIJC"},
{"httpMethod":"get","path":"user/signup/LIVXBDOHJQ/WFELYOHISC"},
{"httpMethod":"post","path":"cargo/tracking/DQSEKCRTUH/ACXGMFBPQW"},
{"httpMethod":"get","path":"user/signup/ORWIQLXKMT/RAOCTWMPLN"},
{"httpMethod":"post","path":"cargo/tracking/RHULFTYDSM/WZLIOYXHUJ"},
{"httpMethod":"get","path":"user/signup/AXLGEFSIHT/GZCVHJUOFT"},
{"httpMethod":"post","path":"cargo/tracking/GNMTDPZRLU/HGFIMJDYSW"},
{"httpMethod":"get","path":"user/signup/MVRLBEIOZQ/CWAUGQFZBJ"},
{"httpMethod":"post","path":"cargo/tracking/CRQKTJONWV/JRIAPVMSDU"},
{"httpMethod":"get","path":"user/signup/QWYJOTRXVB/AWFEDHPUSK"},
{"httpMethod":"post","path":"cargo/tracking/MQAFZGUYOC/OSGNLRDMEK"},
{"httpMethod":"get","path":"user/signup/PQUFMGYAEK/JHQAKUEZGT"},
{"httpMethod":"post","path":"cargo/tracking/SFWYCQATXB/XZCWBSLTAP"},
{"httpMethod":"get","path":"user/signup/SVIWRKBFYJ/DUXZSJGFAH"},
{"httpMethod":"post","path":"cargo/tracking/JYUARTWOHF/HFUALKDSMW"},
{"httpMethod":"get","path":"user/signup/MSBUZDKGHA/IUGLATFBZR"},
{"httpMethod":"post","path":"cargo/tracking/ATYZKOIUXS/ADBGMWKOLZ"},
{"httpMethod":"get","path":"user/signup/RLXHPBSYWQ/NOMWFCYJKA"},
{"httpMethod":"post","path":"cargo/tracking/TREOKJSLQW/BWAFZGKHQP"},
{"httpMethod":"get","path":"user/signup/ZVXRUKYJPE/OBDTKZCWFR"},
{"httpMethod":"post","path":"cargo/tracking/RSPFTCJWZI/EPAUXSOBVN"},
{"httpMethod":"get","path":"user/signup/JAXMZLYPDH/XBJYMKUDAN"},
{"httpMethod":"post","path":"cargo/tracking/MODTPLBREK/QFUCLMKAZS"},
{"httpMethod":"get","path":"user/signup/TZMJVXDYLK/PVQEKRCDAX"},
{"httpMethod":"post","path":"cargo/tracking/QIROPABKSC/BENHSJCRKY"},
{"httpMethod":"get","path":"user/signup/DNEUXRIYOW/OJANHCIWSP"},
{"httpMethod":"post","path":"cargo/tracking/QCIRJEUDVN/TWFKHOMAUP"},
{"httpMethod":"get","path":"user/signup/FHYEMOCUTJ/KMFINEZHGJ"},
{"httpMethod":"post","path":"cargo/tracking/KBWTVPSOCY/DREJHPOINL"},
{"httpMethod":"get","path":"user/signup/CXZTSFBEPA/FBIDJVMWZT"},
{"httpMethod":"post","path":"cargo/tracking/DTSAGBYUNF/KPBIGHCYJQ"},
{"httpMethod":"get","path":"user/signup/HDGVKSNQMJ/RWSKQLTAJB"},
{"httpMethod":"post","path":"cargo/tracking/LUJDBCTVNZ/DZPLYXUSOV"},
{"httpMethod":"get","path":"user/signup/XNDYPKVCGW/UFKERBOJDX"}
];

for(let e of testData){
  var g = router.jparse(e); 
  console.log(g);
}
